version: '3.4'
services:
  mysql-server:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: test123
    volumes:
      - db:/var/lib/mysql
    networks:
      - db-network

  pmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8000:80
    depends_on:
      - mysql-server
    environment:
      - PMA_PASSWORD=test123
    networks:
      - db-network
volumes:
  db:
networks:
   db-network: